config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'read', to: 'articles#read'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
   end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def read
    @articles = Article.where(read: true)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <h1>New Article</h1>
    <%= form_for(article) do |f| %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

      <%= f.submit class: 'btn btn-primary mb-5' %>
    <% end %>

<%= link_to "back", articles_path%>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/read.html.erb
<div class="container">
  <% @articles.each do |article| %>

  <h2><%= link_to article.title, article_path(article)  %></h2>
  <p><%= article.content %></p>
  <% end %>


</div>

app/views/articles/show.html.erb
<div class="container">
  <h1 class="pb-5 border-bottom"><%= @article.title %>
    <%= link_to edit_article_path(@article) do %>
      <i class="fas fa-pencil-alt" style="font-size: 0.5em"></i>
    <% end %>
    <%= link_to article_path(@article), method: :delete, data: { confirm: "are you sure?"} do %>
      <i class="fas fa-trash-alt" style="font-size: 0.5em"></i>
    <% end %>
    <% unless @article.read %>
      <%= link_to article_path(@article, article: {read: true}), method: :put do %>
        <i class="fas fa-book" style="font-size: 0.5em"></i>
        <% end %>
    <% end %>
  </h1>

<p><%= @article.content %></p>


<%= link_to "back", articles_path  %>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex justify-content-between bg-light p-3 mb-5 border-bottom">
        <%= link_to 'Wikinimous', articles_path, class: 'text-decoration-none text-secondary' %>
        <div class="d-flex">
          <%= link_to "add new article", new_article_path, class: 'text-decoration-none text-secondary mr-5' %>
          <%= link_to 'read articles', read_path, class: 'text-decoration-none text-secondary'  %>
        </div>

    </div>

    <%= yield %>
  </body>
</html>